jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: ci/mac/build
    displayName: 'macOS Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'macOS'
      targetPath: 'ci/mac/bin'
- job: windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: ci/win/build.bat
    displayName: 'Windows Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Windows'
      targetPath: 'ci/win/bin'
