variables:
  - group: Notarize
jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Application.p12'
      certPwd: 'pAVuCweV'
      keychain: 'temp'
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'Installer.p12'
      certPwd: 'pAVuCweV'
      keychain: 'temp'
  - script: ci/mac/build $(username) $(password)
    displayName: 'macOS Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'macOS'
      targetPath: 'ci/mac/bin'
- job: windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: ci/win/build.bat
    displayName: 'Windows Build'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'Windows'
      targetPath: 'ci/win/bin'
